name: SLHawaii
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - xarray
  - ipykernel
  - cartopy
  - seaborn
  - scipy
  - jupyter-book
  - docutils=0.17.1
  - netcdf4
  - dask
  - plotly
  - utide
  - pyextremes
  - great_tables
  - selenium
